### ISSUE TITLE
ImportError: cannot import name 'Sequence'

### ISSUE THREAD

**Issue by btcooper22** [jgraving/DeepPoseKit#44]
When trying to import deepposekit, I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\benco\Anaconda3\envs\deepposekit\lib\site-packages\deepposekit\__init__.py", line 20, in <module>
    from deepposekit.io import TrainingGenerator, DataGenerator
  File "C:\Users\benco\Anaconda3\envs\deepposekit\lib\site-packages\deepposekit\io\__init__.py", line 25, in <module>
    from deepposekit.io.video import *
  File "C:\Users\benco\Anaconda3\envs\deepposekit\lib\site-packages\deepposekit\io\video.py", line 16, in <module>
    from tensorflow.python.keras.utils import Sequence
ImportError: cannot import name 'Sequence'

As far as I can tell, TensorFlow 2.1.0 is installed fine. It's certainly able to find my GPU.

Thanks,
Ben

**Comment by jgraving** [comment]
This should already be fixed in https://github.com/jgraving/DeepPoseKit/commit/b3bb5398b23358fd41e6fa9a38743874a2233775 Make sure you have the latest release of DPK installed

**Comment by btcooper22** [comment]
I seem to have. 0.3.6? Reverting back to tensorflow 2.0.0 seems to have fixed the issue.

**Comment by jgraving** [comment]
I pushed the wrong version to pip. Should be fixed now.
