### ISSUE TITLE
Unable to open object (object 'logs' doesn't exist)

### ISSUE THREAD

**Issue by albertoursino** [jgraving/DeepPoseKit#72]
Can someone help me with this error?

```python
Epoch 00001: loss improved from inf to 31.71337, saving model to C:/Users/Alberto Ursino/Desktop/IntellIj Local Files/DeepPoseKit/alberto/deepposekit-data/datasets/dog/log_densenet.h5
C:\Users\Alberto Ursino\Desktop\IntellIj Local Files\DeepPoseKit\deepposekit\models\engine.py:196: UserWarning: `n_validation` is 0, so the training set will be used for model evaluation
  "`n_validation` is 0, so the training set will be used for model evaluation"
Traceback (most recent call last):
  File "C:/Users/Alberto Ursino/Desktop/IntellIj Local Files/DeepPoseKit/alberto/annotation/train.py", line 180, in <module>
    steps_per_epoch=1,
  File "C:\Users\Alberto Ursino\Desktop\IntellIj Local Files\DeepPoseKit\deepposekit\models\engine.py", line 174, in fit
    **kwargs
  File "C:\Users\Alberto Ursino\anaconda3\envs\TensorFlow 1x\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\Alberto Ursino\anaconda3\envs\TensorFlow 1x\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\Alberto Ursino\anaconda3\envs\TensorFlow 1x\lib\site-packages\tensorflow\python\keras\callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Alberto Ursino\Desktop\IntellIj Local Files\DeepPoseKit\deepposekit\callbacks.py", line 126, in on_epoch_end
    data = h5file["logs"][key]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Alberto Ursino\anaconda3\envs\TensorFlow 1x\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'logs' doesn't exist)"
```

These are the parameters I have set:
```python
model.fit(
    batch_size=16,
    validation_batch_size=10,
    callbacks=callbacks,
    #epochs=1000, # Increase the number of epochs to train the model longer
    epochs=200,
    n_workers=8,
    steps_per_epoch=1,
)
```

**Comment by albertoursino** [comment]
Ouch, I have found the error.
![image](https://user-images.githubusercontent.com/56396708/101426632-a3bebd80-38fd-11eb-946f-36a5c39ab410.png)
The two files I have outlined must have different names....
