### ISSUE TITLE
Deepposekit-annotation

### ISSUE THREAD

**Issue by liuxi1998** [jgraving/DeepPoseKit#95]
Traceback (most recent call last):
  File "/Users/liuximac/deepposekit-data/datasets/fly/02.annotate.py", line 11, in <module>
    app.run()
  File "/Users/liuximac/miniconda3/envs/tf/lib/python3.9/site-packages/deepposekit/annotate/gui/GUI.py", line 657, in run
    self._hotkeys()
  File "/Users/liuximac/miniconda3/envs/tf/lib/python3.9/site-packages/deepposekit/annotate/gui/Annotator.py", line 332, in _hotkeys
    self._data()
  File "/Users/liuximac/miniconda3/envs/tf/lib/python3.9/site-packages/deepposekit/annotate/gui/Annotator.py", line 316, in _data
    self._save()
  File "/Users/liuximac/miniconda3/envs/tf/lib/python3.9/site-packages/deepposekit/annotate/gui/Annotator.py", line 201, in _save
    h5file["annotations"][self.image_idx] = self.skeleton.loc[
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/liuximac/miniconda3/envs/tf/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 951, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: Can't write data (no write intent on file)

**Comment by liuxi1998** [comment]
The image I marked can't be saved successfully? Why?
